repos:
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-flake8
    rev: v3.9.2
    hooks:
      - id: flake8

  - repo: https://github.com/duncanmmacleod/gherkin-lint-precommit
    rev: v0.2.0
    hooks:
      - id: gherkin-lint
